model:
  initial_view: [-0.0, 0.0, 1.2]
  normalization: True
  use_lipschitz: True
  use_1DNorm: False
  lip_const: 1.0
  loss_n_hype: -0.1
  sym_op_type: "Sphere" # L1, Sphere, 
  sym_div_hype: 50
  sym_mult_hype: 50
  layer_sizes: [64, 64, 64, 64, 256]
  contour_density: 0.5
  batch_size: 200000
  frame_epoch: 3000

region:
  use_predefined: False
  columns: 3 # x
  rows: 3 # y
  boundaries: [-10, 10, -6, 14]


  #! Predefined regions
  regions:
    - [-10, 10, -6, 14]
    # - [-10.5, 25.5, -45.5, 2.5]

  region_combination:
    - [0, 1, 2, 3, 4, 5, 6, 7, 8]


data:
  center: [0, 4, 1.5]
  offset: [10, 10, 2]
  limit: [10, 10, 2]
  dim: 3
  scaling: 1.0
  minimum: 0.04
  maximum: 0.4 # 1.0
  wallsize: 0.00
  sample_num: 500000


paths:
  name: 'almena'
  meshpath: './data/almena.obj'
  # pointspath: './data/cube_passage_empty_points.npy'
  # speedspath: './data/cube_passage_empty_speeds.npy'
