model:
  initial_view: [-0.0, 3.5, -0.0]
  normalization: True
  use_lipschitz: True
  use_1DNorm: False
  lip_const: 1.0
  loss_n_hype: -0.1
  sym_op_type: "L1_new" # L1, Sphere, L2, L1_sqrt, L1_new
  sym_div_hype: 50
  sym_mult_hype: 50
  layer_sizes: [64, 64, 64, 64, 256]
  contour_density: 0.2
  batch_size: 200000
  frame_epoch: 5000


region:
  use_predefined: False
  use_merge: False
  columns: 5 # * | * | * | * | *
  rows: 5 # =
  # boundaries: [-3.5, 3.5, -3.5, 3.5]
  overlap_ratio: 0.25


  #! Predefined regions
  regions:
    - [-3.5, 3.5, -3.5, 3.5]

  region_combination:
    - [0]

data:
  center: [0, 0, 0]
  offset: [3.2, 5, 1]
  limit: [3.2, 5, 1.1]
  dim: 3
  scaling: 1.0
  minimum: 0.02
  maximum: 0.2 # 1.0
  wallsize: 0.00
  sample_num: 500000

occ_map:
  dim_cells: 120
  minimum: 0.01
  maximum: 0.1
  occ_threshold: 0.8 # larger than this value is occupied
  occupied_area_threshold: 0.1 # smaller than this value is considered okay to include valid block


paths:
  name: 'Auburn'
  folder: './data/gibson'


