model:
  initial_view: [-1.5, 1.0, 0]
  normalization: True
  use_lipschitz: False
  loss_n_hype: -0.1
  sym_div: True # whether to divide scale
  sym_div_hype: 500
  sym_mult_hype: 50
  layer_sizes: [64, 64, 64, 64, 256]

regions:
  - [-6, 0, 0, 6]
  - [-3, 3, 0, 6]
  - [0, 6, 0, 6]
  - [-6, 0, -3, 3]
  - [-3, 3, -3, 3]
  - [0, 6, -3, 3]
  - [-6, 0, -6, 0]
  - [-3, 3, -6, 0]
  - [0, 6, -6, 0]

data:
  center: [0, 0, 0]
  offset: [3.0, 3.0, 3.0]
  dim: 3
  scaling: 6.0
  minimum: 0.01
  maximum: 0.1
  sample_num: 200000

paths:
  meshpath: './data/cabin_mesh.obj'
  pointspath: './data/cabin_points.npy'
  speedspath: './data/cabin_speeds.npy'
