model:
  initial_view: [-2.0, 2.0, -0.0]
  normalization: True
  use_lipschitz: True
  use_1DNorm: False
  lip_const: 1.0
  loss_n_hype: -0.1
  sym_div: True # whether to divide scale
  sym_div_hype: 50
  sym_mult_hype: 50
  layer_sizes: [64, 64, 64, 64, 256]
  contour_density: 0.1
  batch_size: 200000

# regions:
#   - [-6, 0, 0, 6]
#   - [-3, 3, 0, 6]
#   - [0, 6, 0, 6]
#   - [-6, 0, -3, 3]
#   - [-3, 3, -3, 3]
#   - [0, 6, -3, 3]
#   - [-6, 0, -6, 0]
#   - [-3, 3, -6, 0]
#   - [0, 6, -6, 0]

# regions:
#   - [-7, -1, 0, 6]
#   - [1, 7, 0, 6]
#   - [-7, -1, -3, 3]
#   - [1, 7, -3, 3]
#   - [-7, -1, -6, 0]
#   - [-3, 3, -6, 0]
#   - [1, 7, -6, 0]

# regions:
#   - [-7, -1, 0, 6]
#   - [-7, -1, -3, 3]
#   - [-7, -1, -6, 0]
#   - [-3, 3, -6, 0]
#   - [1, 7, -6, 0]
#   - [1, 7, -3, 3]
#   - [1, 7, 0, 6]

regions:
  - [-3.5, -0.5, 0.5, 3.5]
  - [-3.5, -0.5, -1.5, 1.5]
  - [-3.5, -0.5, -3.5, -0.5]
  - [-1.5, 1.5, -3.5, -0.5]
  - [0.5, 3.5, -3.5, -0.5]
  - [0.5, 3.5, -1.5, 1.5]
  - [0.5, 3.5, 0.5, 3.5]
  - [-1.5, 1.5, 0.5, 3.5]

# region_combination:
#   - [0, 1]
#   - [0, 1, 2]
#   - [0, 1, 2, 3]
#   - [0, 1, 2, 3, 4]
#   - [0, 1, 2, 3, 4, 5]
#   - [0, 1, 2, 3, 4, 5, 6]
#   - [0, 1, 2, 3, 4, 5, 6, 7]


region_combination:
  - [0, 1]
  - [1, 2]
  - [2, 3]
  - [3, 4]
  - [4, 5]
  - [5, 6]
  - [6, 7]

# regions:
#   - [-3.5, 3.5, -3.5, 3.5]

# region_combination:
#   - [0]

data:
  center: [0, 0, 0]
  offset: [3, 3, 3]
  limit: [3.5, 3.5, 3.5]
  dim: 3
  scaling: 1.0
  minimum: 0.1
  maximum: 1.0 # 1.0
  wallsize: 0.00
  sample_num: 500000

paths:
  name: 'cube_passage'
  meshpath: './data/cube_passage.obj'
  pointspath: './data/cube_passage_empty_points.npy'
  speedspath: './data/cube_passage_empty_speeds.npy'
