model:
  initial_view: [-0.3, -0.2, -0.]
  normalization: False
  use_lipschitz: False
  loss_n_hype: -2.0
  sym_div: True # whether to divide scale
  sym_div_hype: 50
  sym_mult_hype: 50
  layer_sizes: [64, 64, 64, 64, 256]
  contour_density: 0.02

# regions:
#   - [-1, 1, -1, 1]

# regions:
#   - [-1, 0, 0, 1]
#   - [-0.5, 0.5, 0, 1]
#   - [0, 1, 0, 1]
#   - [-1, 0, -0.5, 0.5]
#   - [-0.5, 0.5, -0.5, 0.5]
#   - [0, 1, -0.5, 0.5]
#   - [-1, 0, -1, 0]
#   - [-0.5, 0.5, -1, 0]
#   - [0, 1, -1, 0]

# region_combination:
#   - [0, 1, 2, 3, 4, 5, 6, 7, 8]

regions:
  - [-1, 1, -1, 1]


region_combination:
  - [0]


data:
  center: [0, 0, 0]
  offset: [0.5, 0.5, 0.5]
  dim: 3
  scaling: 1.0
  minimum: 0.005
  maximum: 0.05
  sample_num: 200000

paths:
  name: 'mesh'
  meshpath: './data/mesh.obj'
  pointspath: './data/mesh_points.npy'
  speedspath: './data/mesh_speeds.npy'
